language: python
notifications:
  email:
    recipients:
      - 944921374@qq.com
    on_success: change
    on_failure: always
python:
  - 3.6
before_install:
  - pip install -r requirements.txt
script:
  - python email_say_hello.py
